# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 579c74db8829d5dc8c36ba46b881772052bf8b7b864aba2b78251867bfb734068f15264b1cbc529cf5329946b3aa8653ff9a465f1a8c777eaf3714efbcf044ff

test:
  secret_key_base: da320ac404342691df60bce5581212be62bbea353fcf959e16430474b7b6f52679a32bce0772776a07840ce6dbc9ee792795e7e90ef54d56f49cef548a40f9a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
